.TH suse-rancher-setup-plugin "8" "07 Dec 2022" "suse-rancher-setup-plugin" "Support Utilities Manual"
.SH NAME
suse-rancher-setup-plugin \- SUSE Rancher Setup Plugin for
.BR supportconfig (8)
.
.SH DESCRIPTION
Supportconfig plugins add functionality to the supportconfig script. This
plugin extends supportconfig's functionality to include pertinent information
for instances running SUSE Rancher Setup. Supportconfig saves the plugin output
in the rancher_setup subdirectory.

.SH FILES
.I /usr/lib/supportconfig/plugins/suse_rancher_setup
.RS

The SUSE Rancher Setup plugin for supportutils
.RE
.SH AUTHOR
SUSE Public Cloud Engineering Team <public-cloud-dev@susecloud.net>
.SH REPORTING BUGS
Please submit bug fixes, comments or enhancement requests via:
.B https://github.com/SUSE-Enceladus/supportutils-plugin-suse-rancher-setup/issues
.SH SEE ALSO
.BR supportconfig (8)
.BR supportconfig.conf (5)
